/*
 * Copyright (C) 2025 Hacker's Keyboard contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package org.pocketworkstation.pckeyboard;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.Reader;
import java.text.Normalizer;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * The emoji catalogue: categories, skin tone variants and search keywords.
 *
 * Parsed from the files generated by tools/emoji/gen_emoji_data.py. This class
 * has no Android dependencies so that it can be unit tested on the JVM.
 */
public class EmojiData {

    /** Decides whether the device can render an emoji sequence as one glyph. */
    public interface GlyphChecker {
        boolean canRender(String emoji);
    }

    public static class Emoji {
        /** The emoji without skin tone, as inserted by default. */
        public final String base;
        /** Emoji version the base emoji was introduced in, e.g. 13.1. */
        public final float version;
        /**
         * Skin tone variants: either 5 (one per tone) or 25 (a 5x5 grid of
         * tone combinations for two-person emoji, row-major), or none.
         */
        public String[] variants;
        public final int category;
        /** Position in the full catalogue, used as a stable ranking tie breaker. */
        final int order;
        /** Normalized search terms: whole name, name words and keywords. */
        final ArrayList<String> terms = new ArrayList<String>();
        /** Normalized full names, one per loaded language. */
        final ArrayList<String> names = new ArrayList<String>();
        final ArrayList<String> nameWords = new ArrayList<String>();
        /** Words in the shortest name; shorter names are more specific matches. */
        int nameLength = Integer.MAX_VALUE;
        String name;

        Emoji(String base, float version, String[] variants, int category, int order) {
            this.base = base;
            this.version = version;
            this.variants = variants;
            this.category = category;
            this.order = order;
        }

        public boolean hasVariants() {
            return variants.length > 0;
        }

        /** Localized name from the first keyword file that had one, or null. */
        public String getName() {
            return name;
        }

        @Override
        public String toString() {
            return base;
        }
    }

    public static class Category {
        public final String id;
        public final List<Emoji> emoji = new ArrayList<Emoji>();

        Category(String id) {
            this.id = id;
        }
    }

    private static final String[] NO_VARIANTS = new String[0];

    private final List<Category> mCategories = new ArrayList<Category>();
    /** Every base and variant form -> its emoji. */
    private final Map<String, Emoji> mByForm = new HashMap<String, Emoji>();
    private final List<Emoji> mAll = new ArrayList<Emoji>();

    public List<Category> getCategories() {
        return mCategories;
    }

    public List<Emoji> getAll() {
        return mAll;
    }

    /** Looks up an emoji by its base or any of its skin tone variants. */
    public Emoji find(String form) {
        Emoji e = mByForm.get(form);
        if (e == null && form.indexOf('\uFE0F') >= 0) {
            e = mByForm.get(form.replace("\uFE0F", ""));
        }
        return e;
    }

    public static EmojiData parse(Reader in) throws IOException {
        EmojiData data = new EmojiData();
        BufferedReader reader = new BufferedReader(in);
        Category category = null;
        String line;
        while ((line = reader.readLine()) != null) {
            if (line.isEmpty() || line.startsWith("#")) continue;
            if (line.startsWith("@")) {
                category = new Category(line.substring(1).trim());
                data.mCategories.add(category);
                continue;
            }
            if (category == null) throw new IOException("emoji before first category: " + line);
            String[] parts = line.split(" ");
            if (parts.length < 2) throw new IOException("bad emoji line: " + line);
            String[] variants = NO_VARIANTS;
            if (parts.length > 2) {
                variants = new String[parts.length - 2];
                System.arraycopy(parts, 2, variants, 0, variants.length);
            }
            float version;
            try {
                version = Float.parseFloat(parts[1]);
            } catch (NumberFormatException e) {
                throw new IOException("bad emoji version: " + line);
            }
            Emoji emoji = new Emoji(parts[0], version, variants,
                    data.mCategories.size() - 1, data.mAll.size());
            category.emoji.add(emoji);
            data.mAll.add(emoji);
        }
        data.reindex();
        return data;
    }

    private void reindex() {
        mByForm.clear();
        for (Emoji e : mAll) {
            mByForm.put(e.base, e);
            mByForm.put(e.base.replace("\uFE0F", ""), e);
            for (String v : e.variants) mByForm.put(v, e);
        }
    }

    /**
     * Removes emoji the device cannot render, and skin tone variants that are
     * only partially supported. Two-person emoji whose mixed tone combinations
     * are unsupported fall back to the five same-tone variants.
     */
    public void filter(GlyphChecker checker, boolean allowVariants) {
        mAll.clear();
        for (Category category : mCategories) {
            List<Emoji> kept = new ArrayList<Emoji>(category.emoji.size());
            for (Emoji e : category.emoji) {
                if (!checker.canRender(e.base)) continue;
                e.variants = allowVariants ? supportedVariants(e.variants, checker) : NO_VARIANTS;
                kept.add(e);
            }
            category.emoji.clear();
            category.emoji.addAll(kept);
            mAll.addAll(kept);
        }
        reindex();
    }

    private static String[] supportedVariants(String[] variants, GlyphChecker checker) {
        if (allRenderable(variants, checker)) return variants;
        if (variants.length == 25) {
            String[] sameTone = new String[5];
            for (int i = 0; i < 5; ++i) sameTone[i] = variants[i * 6];
            if (allRenderable(sameTone, checker)) return sameTone;
        }
        return NO_VARIANTS;
    }

    private static boolean allRenderable(String[] forms, GlyphChecker checker) {
        for (String f : forms) {
            if (!checker.canRender(f)) return false;
        }
        return true;
    }

    /**
     * Adds names and keywords from a keywords_<lang>.txt file. Can be called
     * for several languages; the first language to provide a name wins.
     */
    public void addKeywords(Reader in) throws IOException {
        BufferedReader reader = new BufferedReader(in);
        String line;
        while ((line = reader.readLine()) != null) {
            if (line.isEmpty() || line.startsWith("#")) continue;
            String[] parts = line.split("\t", -1);
            if (parts.length < 3) continue;
            Emoji e = mByForm.get(parts[0]);
            if (e == null) continue; // filtered out on this device
            if (e.name == null && !parts[1].isEmpty()) e.name = parts[1];
            String name = normalize(parts[1]);
            addTerm(e.names, name);
            addTerm(e.terms, name);
            List<String> words = splitWords(name);
            if (!words.isEmpty()) e.nameLength = Math.min(e.nameLength, words.size());
            for (String word : words) {
                addTerm(e.terms, word);
                addTerm(e.nameWords, word);
            }
            if (parts[2].isEmpty()) continue;
            for (String keyword : parts[2].split("\\|")) {
                keyword = normalize(keyword);
                addTerm(e.terms, keyword);
                for (String word : splitWords(keyword)) addTerm(e.terms, word);
            }
        }
    }

    private static void addTerm(List<String> terms, String term) {
        if (!term.isEmpty() && !terms.contains(term)) terms.add(term);
    }

    private static List<String> splitWords(String s) {
        List<String> words = new ArrayList<String>();
        for (String w : s.split("[\\s:,.()\u201C\u201D\"!?-]+")) {
            if (!w.isEmpty()) words.add(w);
        }
        return words;
    }

    /** Lower case and strip accents so that "hande" finds "Hände". */
    static String normalize(String s) {
        String lower = s.toLowerCase(Locale.ROOT).trim();
        String decomposed = Normalizer.normalize(lower, Normalizer.Form.NFD);
        StringBuilder out = new StringBuilder(decomposed.length());
        for (int i = 0; i < decomposed.length(); ++i) {
            char c = decomposed.charAt(i);
            if (Character.getType(c) != Character.NON_SPACING_MARK) out.append(c);
        }
        return Normalizer.normalize(out, Normalizer.Form.NFC);
    }

    /** Enough text to hold the longest emoji sequence (a two-person kiss with skin tones). */
    public static final int MAX_SEQUENCE_LENGTH = 32;

    /**
     * Length in chars of the grapheme ending {@code text}, treating emoji
     * sequences (ZWJ sequences, skin tones, keycaps, tag sequences and
     * regional indicator flags) as one unit, so backspace can remove them
     * at once.
     */
    public static int lastSequenceLength(CharSequence text) {
        final int end = text.length();
        int i = end;
        while (i > 0) {
            int cp = Character.codePointBefore(text, i);
            i -= Character.charCount(cp);
            if (isEmojiModifier(cp)) continue;
            if (isRegionalIndicator(cp)) {
                // Flags are pairs of regional indicators, paired from the start of the run.
                int run = 1;
                for (int j = i; j > 0 && isRegionalIndicator(Character.codePointBefore(text, j)); j -= 2) {
                    ++run;
                }
                if (run % 2 == 0) i -= 2;
            }
            // Joined to the previous emoji: keep going. Indic scripts use ZWJ
            // inside words too (क्‍ष), those are left to the editor.
            if (i > 1 && text.charAt(i - 1) == ZWJ && isEmojiBase(cp)
                    && isEmojiBase(Character.codePointBefore(text, i - 1))) {
                --i;
                continue;
            }
            break;
        }
        return end - i;
    }

    private static final char ZWJ = '\u200D';

    /** Code points that attach to the preceding character. */
    private static boolean isEmojiModifier(int cp) {
        return cp == 0xFE0F || cp == 0xFE0E       // variation selectors
                || cp == 0x20E3                   // combining keycap
                || (cp >= 0x1F3FB && cp <= 0x1F3FF) // skin tones
                || (cp >= 0xE0020 && cp <= 0xE007F); // tags (subdivision flags)
    }

    /** Code points that can take part in emoji ZWJ sequences. */
    private static boolean isEmojiBase(int cp) {
        return cp >= 0x1F000 // pictographs, supplemental symbols
                || (cp >= 0x2000 && cp <= 0x2BFF) // ♀ ⚕ ❤ ✈ ⬛ ...
                || isEmojiModifier(cp);
    }

    private static boolean isRegionalIndicator(int cp) {
        return cp >= 0x1F1E6 && cp <= 0x1F1FF;
    }

    private static final int SCORE_EXACT_NAME = 100;
    private static final int SCORE_NAME_WORD = 30;
    private static final int SCORE_KEYWORD = 20;
    private static final int SCORE_NAME_PREFIX = 10;
    private static final int SCORE_PREFIX = 5;
    /** For emoji the user uses; less than the gap between the match kinds above. */
    private static final int SCORE_BOOST = 3;

    public List<Emoji> search(String query, int limit) {
        return search(query, limit, Collections.<Emoji>emptySet());
    }

    /**
     * Emoji matching every word of the query, best matches first. A query word
     * matches a term it is a prefix of, so results update while typing.
     * Matches in {@code boosted} (e.g. recently used emoji) rank higher.
     */
    public List<Emoji> search(String query, int limit, Set<Emoji> boosted) {
        String q = normalize(query);
        List<String> words = splitWords(q);
        if (words.isEmpty()) return Collections.emptyList();
        List<Scored> hits = new ArrayList<Scored>();
        for (Emoji e : mAll) {
            int score = 0;
            for (String word : words) {
                int best = 0;
                for (String term : e.nameWords) {
                    if (term.equals(word)) {
                        best = Math.max(best, SCORE_NAME_WORD);
                    } else if (term.startsWith(word)) {
                        best = Math.max(best, SCORE_NAME_PREFIX);
                    }
                }
                for (String term : e.terms) {
                    if (term.equals(word)) {
                        best = Math.max(best, SCORE_KEYWORD);
                    } else if (term.startsWith(word)) {
                        best = Math.max(best, SCORE_PREFIX);
                    }
                }
                if (best == 0) {
                    score = 0;
                    break;
                }
                score += best;
            }
            if (score == 0) continue;
            if (e.names.contains(q)) score += SCORE_EXACT_NAME;
            if (boosted.contains(e)) score += SCORE_BOOST;
            hits.add(new Scored(e, score));
        }
        return best(hits, limit);
    }

    /**
     * Emoji for a whole typed word, for the suggestion strip: the word must be
     * a complete name word or keyword, not just a prefix.
     * Matches in {@code boosted} (e.g. recently used emoji) rank higher.
     */
    public List<Emoji> suggest(String word, int limit) {
        return suggest(word, limit, Collections.<Emoji>emptySet());
    }

    /**
     * Words too common to suggest emoji for while typing, although CLDR lists
     * them as keywords ("not" for ⛔, "you" for 🥰). Search still finds them.
     */
    private static final Set<String> SUGGEST_STOP_WORDS = new HashSet<String>(Arrays.asList(
            "and", "are", "but", "can", "for", "get", "got", "not", "the", "too",
            "was", "you", "your"));

    public List<Emoji> suggest(String word, int limit, Set<Emoji> boosted) {
        String w = normalize(word);
        if (w.length() < 2) return Collections.emptyList();
        List<Scored> hits = new ArrayList<Scored>();
        for (Emoji e : mAll) {
            int score = 0;
            if (e.names.contains(w)) {
                score = SCORE_EXACT_NAME;
            } else if (w.length() < 3 || SUGGEST_STOP_WORDS.contains(w)) {
                // Short and common words only suggest emoji named exactly that.
            } else if (e.nameWords.contains(w)) {
                score = SCORE_NAME_WORD;
            } else if (e.terms.contains(w)) {
                score = SCORE_KEYWORD;
            }
            if (score == 0) continue;
            if (boosted.contains(e)) score += SCORE_BOOST;
            hits.add(new Scored(e, score));
        }
        return best(hits, limit);
    }

    private static List<Emoji> best(List<Scored> hits, int limit) {
        Collections.sort(hits);
        List<Emoji> result = new ArrayList<Emoji>(Math.min(limit, hits.size()));
        for (int i = 0; i < hits.size() && i < limit; ++i) result.add(hits.get(i).emoji);
        return result;
    }

    private static class Scored implements Comparable<Scored> {
        final Emoji emoji;
        final int score;

        Scored(Emoji emoji, int score) {
            this.emoji = emoji;
            this.score = score;
        }

        @Override
        public int compareTo(Scored other) {
            if (score != other.score) return other.score - score;
            if (emoji.nameLength != other.emoji.nameLength) {
                return emoji.nameLength < other.emoji.nameLength ? -1 : 1;
            }
            return emoji.order - other.emoji.order;
        }
    }
}
